# Generated by Django 3.2.4 on 2021-06-29 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNo', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('DOB', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ("Don't Say", "Don't Say")], max_length=100)),
                ('Age', models.IntegerField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_classes.student_class')),
            ],
        ),
    ]
