# Generated by Django 3.2.4 on 2021-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('class_name_in_numeric', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
