# Generated by Django 3.2.4 on 2021-06-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=100)),
                ('sub_creation_code', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject_combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_classes.student_class')),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject_detail')),
            ],
        ),
    ]
