# Generated by Django 3.2.4 on 2021-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_detail',
            name='sub_creation_code',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
